### ISSUE TITLE
Persistence Api and implementation mismatch

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-persistence-spanner#146]
While adapting the implementation of the Durable State store for Spanner to the Akka Persistence Durable State API in #145 we noticed some mistmach.

The issue is that certain operations on the internal implementation expect an `entityType` while the Akka API doesn't have access to it. The higher issue is that in the Akka Persistence API, once a `PersistenceId` is created, the access to the `type_hint` (aka `entityType`)  and the `entityId` is no longer possible.

Another consequence of this mismatch is the `state` table in spanner now has a new column named `tag` that may be set if the user interacts with the plugin using the Akka Persistence API.

This issue is likely to escalate into akka core so that the Akka Persistence API is extended to expose `type_hint`.

**Comment by patriknw** [comment]
The entity_type vs tag has been solved in https://github.com/akka/akka-persistence-spanner/pull/149
