### ISSUE TITLE
Duplicate class files

### ISSUE THREAD

**Issue by hseeberger** [akka/akka-persistence-spanner#62]
When trying to `assembly` the Cloudstate Proxy for Spanner, which is using this library, we ended up with duplicate files with different contents. These come from Scala files created by the protobuf compiler. As both this library and our project are using akka-grpc this is not surprising.

Now the question is whether it is necessary for this library to actually include the class files or if it could be possible to make them "provided", either as separate JAR or just as .proto-files to be included.

```
[error] (assembly) deduplicate: different file contents found in the following:
[error] GoogleInternetAuthorityG3.crt
[error] /Users/heiko/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/lightbend/akka/akka-persistence-spanner_2.12/0.1/akka-persistence-spanner_2.12-0.1.jar:GoogleInternetAuthorityG3.crt
[error] deduplicate: different file contents found in the following:
[error] /Users/heiko/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/lightbend/akka/akka-persistence-spanner_2.12/0.1/akka-persistence-spanner_2.12-0.1.jar:com/google/protobuf/any/Any$.class
[error] /Users/heiko/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/thesamet/scalapb/scalapb-runtime_2.12/0.10.2/scalapb-runtime_2.12-0.10.2.jar:com/google/protobuf/any/Any$.class
[error] deduplicate: different file contents found in the following:
[error] /Users/heiko/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/lightbend/akka/akka-persistence-spanner_2.12/0.1/akka-persistence-spanner_2.12-0.1.jar:com/google/protobuf/any/Any$AnyLens.class
...
```

**Comment by chbatey** [comment]
I don't think it makes sense for us to make mandatory dependencies provided. I think downstream projects that want to override to a different version should do so explicitly to be aware that it may not work. 

The plugin is compiled against a specific version of Akka gRPC which in turn is a specific version of the scalapb runtime. I don't think it is wise to mix and match generated code from different versions of Akka gRPC and if cloudstate were to generate it with an older version (as is the case here I think) it likely won't work.

For Akka gRPC this becomes easier for 1.0 when it plans to offer binary compatibility for generated code, but in this case you'd have to use the newer version of Akka gRPC.

**Comment by raboof** [comment]
> I don't think it makes sense for us to make mandatory dependencies provided

I agree, but there is something else we could do: in the specific example of `com/google/protobuf/any/Any$.class`, akka-persistence-spanner could add a dependency on scalapb-runtime instead of generating code for this class.

Akka gRPC gives some control over which files are generated and which files are 'assumed to exist' by providing the `protobuf` and `protobuf-src` scopes (https://doc.akka.io/docs/akka-grpc/current/buildtools/sbt.html#loading-proto-files-from-artifacts), but I'm not sure if that is sufficient already.

**Comment by viktorklang** [comment]
I think it is dubious to include classes for other packages than the akka-namespace in this jar. Especially "com.google" ones :S

**Comment by raboof** [comment]
@hseeberger @viktorklang is there a cloudstate branch that I can reproduce this with?

**Comment by hseeberger** [comment]
Will push later.

**Comment by chbatey** [comment]
The other is the crt which we can remove in #75
