### ISSUE TITLE
Document that deletion of events impacts queries immediately

### ISSUE THREAD

**Issue by patriknw** [akka/akka-persistence-spanner#81]
Deleting events means that the tagged rows are also deleted at the same time, which should be documented. Important to know for projections (eventsByTag) that can be reading behind but don't want to miss events. In other words, don't delete too early.

**Comment by johanandren** [comment]
I'll have to verify with the new schema because I did not add `ON DELETE CASCADE` in the in #80 so not quite sure what happens when you try to delete a parent row that still has interleaved rows.

**Comment by johanandren** [comment]
Ok, verified, with the interleaved table you get an integrity constraint violation error and it refuses to delete. So we probably need to either never actually delete, or make that configurable so that if you use tags you disable actual delete and only insert into the metadata table.

**Comment by johanandren** [comment]
After some more discussion we'll go with cascade and hard deletes, I'll add that and cos as a part of #80
